config/routes.rb
Rails.application.routes.draw do
  resources :user_books
  resources :users
  root 'user_books#index'

# root "books#index"

  resources :books do
    member do
      get :delete
    end
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/book.rb
class Book < ApplicationRecord
    has_many :users, through: :user_books
    has_many :user_books

    validates :title, :author, :price, :publish_date, presence: true
end

app/models/user.rb
class User < ApplicationRecord
    has_many :books, through: :user_books
    has_many :user_books
end

app/models/user_book.rb
class UserBook < ApplicationRecord
    belongs_to :user
    belongs_to :book
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  
  def index
    @books = Book.all
  end

  def show
    @book = Book.find(params[:id])
  end

  def new
    @book = Book.new
  end

  def create
    @book = Book.new(params.require(:book).permit(:title, :author, :price, :publish_date))
    if @book.save
      flash[:notice] = "Book was successfully created"
      redirect_to books_path()
    else
      render('new')
   end
  end

  def edit
    @book = Book.find(params[:id])
  end

  def update
    @book = Book.find(params[:id])
    if @book.update(params.require(:book).permit(:title, :author, :price, :publish_date))
      flash[:notice] = "Book was successfully updated"
      redirect_to book_path(@book)
    else
      render('edit')
    end
  end

  def delete
    @book = Book.find(params[:id])
  end

  def destroy
    @book = Book.find(params[:id])
    @book.destroy
    flash[:notice] = "Book was successfully deleted"
    redirect_to books_path
  end

end

app/controllers/user_books_controller.rb
class UserBooksController < ApplicationController
  before_action :set_user_book, only: %i[ show edit update destroy ]

  # GET /user_books or /user_books.json
  def index
    @user_books = UserBook.all
  end

  # GET /user_books/1 or /user_books/1.json
  def show
  end

  # GET /user_books/new
  def new
    @user_book = UserBook.new
  end

  # GET /user_books/1/edit
  def edit
  end

  # POST /user_books or /user_books.json
  def create
    @user_book = UserBook.new(user_book_params)

    respond_to do |format|
      if @user_book.save
        format.html { redirect_to user_book_url(@user_book), notice: "User book was successfully created." }
        format.json { render :show, status: :created, location: @user_book }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @user_book.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /user_books/1 or /user_books/1.json
  def update
    respond_to do |format|
      if @user_book.update(user_book_params)
        format.html { redirect_to user_book_url(@user_book), notice: "User book was successfully updated." }
        format.json { render :show, status: :ok, location: @user_book }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @user_book.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /user_books/1 or /user_books/1.json
  def destroy
    @user_book.destroy

    respond_to do |format|
      format.html { redirect_to user_books_url, notice: "User book was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user_book
      @user_book = UserBook.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def user_book_params
      params.require(:user_book).permit(:user_id, :book_id)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: %i[ show edit update destroy ]

  # GET /users or /users.json
  def index
    @users = User.all
  end

  # GET /users/1 or /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users or /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to user_url(@user), notice: "User was successfully created." }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1 or /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to user_url(@user), notice: "User was successfully updated." }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1 or /users/1.json
  def destroy
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url, notice: "User was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def user_params
      params.require(:user).permit(:username)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/user_books_helper.rb
module UserBooksHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/delete.html.erb
<%= link_to("Home", books_path)%>
<h1>Delete Book</h1><br>
<p>Are you sure you want to delete this book?</p>
<%= form_for(@book, method: "delete") do |f| %>
<h2><%= @book.title %></h2>



<%= f.submit("Delete Book")%>
<% end %>

app/views/books/edit.html.erb
<%= link_to("Home", books_path)%>
<h2> Edit Book </h2>
<%= form_for(@book) do |f| %>
<table>
    <tr>
        <th>Title</th>
        <td><%= f.text_field(:title)%></td>
    </tr>
    <tr>
        <th>Author</th>
        <td><%= f.text_field(:author)%></td>
    </tr>
    <tr>
        <th>Price</th>
        <td><%= f.text_field(:price)%></td>
    </tr>
    <tr>
        <th>Publish Date (yyyy-dd-yy)</th>
        <td><%= f.text_field(:publish_date)%></td>
    </tr>
</table>
<%= f.submit("Edit Book")%>
<% end %>

app/views/books/index.html.erb
<h1>Library<h1>
<% if flash[:notice] %>
  <div class="notice"><%= flash[:notice] %></div>
<% end %>
<%= link_to("Add New Book", new_book_path, class: "action new")%>
<% @books.each do |book|%>
<div class="book_list_view", display = "flex">
    <h3><%= book.title %></h3><br>
    <h4><%= book.author%></h4><br>
    <p><%= book.publish_date %><p><br>
    <p><%= book.price %><p>
    <%= link_to("Show", book_path(book), class: 'action show')%>
    <%= link_to("Edit", edit_book_path(book), class: 'action edit')%>
    <%= link_to("Delete", delete_book_path(book), class: 'action delete')%>
</div>
<% end %>

app/views/books/new.html.erb
<%= link_to("Home", books_path)%>
<h2> New Book </h2>
<%= form_for(@book) do |f| %>
<table>
    <tr>
        <th>Title</th>
        <td><%= f.text_field(:title)%></td>
    </tr>
    <tr>
        <th>Author</th>
        <td><%= f.text_field(:author)%></td>
    </tr>
    <tr>
        <th>Price</th>
        <td><%= f.text_field(:price)%></td>
    </tr>
    <tr>
        <th>Publish Date (yyyy-dd-yy)</th>
        <td><%= f.text_field(:publish_date)%></td>
    </tr>
</table>
<%= f.submit("Add Book")%>
<% end %>

app/views/books/show.html.erb
<%= link_to("Home", books_path())%>
<% if flash[:notice] %>
  <div class="notice"><%= flash[:notice] %></div>
<% end %>
<h1><%= @book.title %></h1>
<h2><%= @book.author %></h2>
<h3><%= @book.publish_date%></h3>
<h3><%= @book.price%><h3>
<%= link_to("Edit", edit_book_path(@book))%>
<%= link_to("Delete", delete_book_path(@book), class: 'action delete')%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BookCollection</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/user_books/_form.html.erb
<%= form_with(model: user_book) do |form| %>
  <% if user_book.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(user_book.errors.count, "error") %> prohibited this user_book from being saved:</h2>

      <ul>
        <% user_book.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class = 'field'>
    <%= form.label :user_id %>
    <%= form.select :user_id, User.order(:username).map { |user| [user.username, user.id] }, include_blank: true, id: "id_of_the_user_id_select_box" %>
  </div>

  <div>
    <%= form.label :book_id, style: "display: block" %>
    <%= form.select :book_id, Book.order(:title).map { |book| [book.title, book.id] }, include_blank: true, id: "id_of_the_book_id_select_box" %>
  </div>

  <div class = 'actions'>
    <%= form.submit %>
  </div>
<% end %>

app/views/user_books/_user_book.html.erb
<p id='notice'><%= notice%></p>

<h1>User Books</h1>

<table>
  <thead>
    <tr>
      <th>Username</th>
      <th>Book Title</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @user_books.each do |user_book|%>
      <tr>
        <td><%= User.where(id: user_book.user_id).last.username %></td>
        <td><%= Book.where(id: user_book.book_id).last.title%></td>
        <td><%= link_to 'Show', user_book%></td>
        <td><%= link_to 'Edit', edit_user_book_path(user_book)%></td>
        <td><%= link_to 'Destroy', user_book, method: :delete, data: {confirm: 'Are you sure?'}%></td>
      </tr>
    <%end%>
  </tbody>
</table>

<br>

<%= link_to "New User Book", new_user_book_path %>

<br>

<%= link_to "Book index", books_path%>

<br>

<%= link_to 'User index', users_path%>

app/views/user_books/edit.html.erb
<h1>Editing user book</h1>

<%= render "form", user_book: @user_book %>

<br>

<div>
  <%= link_to "Show this user book", @user_book %> |
  <%= link_to "Back to user books", user_books_path %>
</div>

app/views/user_books/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>User books</h1>

<div id="user_books">
  <% @user_books.each do |user_book| %>
    <%= render user_book %>
    <p>
      <%= link_to "Show this user book", user_book %>
    </p>
  <% end %>
</div>

<%= link_to "New user book", new_user_book_path %>

app/views/user_books/new.html.erb
<h1>New user book</h1>

<%= render "form", user_book: @user_book %>

<br>

<div>
  <%= link_to "Back to user books", user_books_path %>
</div>

app/views/user_books/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @user_book %>

<div>
  <%= link_to "Edit this user book", edit_user_book_path(@user_book) %> |
  <%= link_to "Back to user books", user_books_path %>

  <%= button_to "Destroy this user book", @user_book, method: :delete %>
</div>

app/views/users/_form.html.erb
<%= form_with(model: user) do |form| %>
  <% if user.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
        <% user.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :username, style: "display: block" %>
    <%= form.text_field :username %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/users/_user.html.erb
<div id="<%= dom_id user %>">
  <p>
    <strong>Username:</strong>
    <%= user.username %>
  </p>

</div>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render "form", user: @user %>

<br>

<div>
  <%= link_to "Show this user", @user %> |
  <%= link_to "Back to users", users_path %>
</div>

app/views/users/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Users</h1>

<div id="users">
  <% @users.each do |user| %>
    <%= render user %>
    <p>
      <%= link_to "Show this user", user %>
    </p>
  <% end %>
</div>

<%= link_to "New user", new_user_path %>

app/views/users/new.html.erb
<h1>New user</h1>

<%= render "form", user: @user %>

<br>

<div>
  <%= link_to "Back to users", users_path %>
</div>

app/views/users/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @user %>

<div>
  <%= link_to "Edit this user", edit_user_path(@user) %> |
  <%= link_to "Back to users", users_path %>

  <%= button_to "Destroy this user", @user, method: :delete %>
</div>